default:
  image: python:3.6

build_and_test:
  cache:
    paths:
      - requirements-dev.txt
    when: 'on_success'
    key: 'build_and_test'
  script:
    - apt-get update -y && apt-get install -y --fix-missing build-essential gfortran
    - python3 -m venv test-venv
    - bash test-venv/bin/activate
    - git clone https://github.com/daniel-de-vries/xfoil-python.git && pip install ./xfoil-python
    - pip install -r requirements-dev.txt
    - coverage run -m unittest
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
