name: cd

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    uses: octue/.github/.github/workflows/reusable-deploy-cloud-run-service.yml
    with:
      gcp_project_name: octue-openfast
      gcp_project_number: 86611255144
      gcp_region: europe-west3
      gcp_resource_affix: octue
      gcp_service_name: openfast-service
      local_dockerfile: ./Dockerfile
      cloud_run_flags: '--ingress=all --allow-unauthenticated --max-instances=10 --memory=2048Mi'
